name: Deploy

on:
  workflow_dispatch:
    inputs:
      service:
        description: "Service to deploy"
        required: true
        type: choice
        options:
          - server
          - client
          - both

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set image tag
        id: vars
        run: echo "IMAGE_TAG=${GITHUB_SHA::8}" >> "$GITHUB_OUTPUT"

      - name: Show deployment information
        run: |
          echo "Selected service: ${{inputs.service}}"
          echo "Image tag: ${{steps.vars.outputs.IMAGE_TAG}}"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build server image
        if: inputs.service == 'server' || inputs.service == 'both'
        run: |
          docker build \
            --platform linux/amd64 -t ${{secrets.DOCKERHUB_USERNAME}}/graphql-server:${{steps.vars.outputs.IMAGE_TAG}} \
            ./server

      - name: Build Client image
        if: inputs.service == 'client' || inputs.service == 'both'
        run: |
          docker build \
            --build-arg VITE_GRAPHQL_API_URL="${{secrets.VITE_GRAPHQL_API_URL}}" \
            --platform linux/amd64 -t ${{secrets.DOCKERHUB_USERNAME}}/graphql-client:${{steps.vars.outputs.IMAGE_TAG}} \
            ./client

      - name: Push server image
        if: inputs.service == 'server' || inputs.service == 'both'
        run: |
          docker push \
            ${{secrets.DOCKERHUB_USERNAME}}/graphql-server:${{steps.vars.outputs.IMAGE_TAG}}

      - name: Push client image
        if: inputs.service == 'client' || inputs.service == 'both'
        run: |
          docker push \
            ${{secrets.DOCKERHUB_USERNAME}}/graphql-client:${{steps.vars.outputs.IMAGE_TAG}}

      - name: Deploy server to Render
        if: inputs.service == 'server' || inputs.service == 'both'
        run: |
          curl --fail --request POST \
            "${{secrets.RENDER_SERVER_DEPLOY_HOOK}}&imgURL=docker.io/${{secrets.DOCKERHUB_USERNAME}}/graphql-server:${{steps.vars.outputs.IMAGE_TAG}}"

      - name: Deploy client to Render
        if: inputs.service == 'client' || inputs.service == 'both'
        run: |
          curl --fail --request POST \
            "${{secrets.RENDER_CLIENT_DEPLOY_HOOK}}&imgURL=docker.io/${{secrets.DOCKERHUB_USERNAME}}/graphql-client:${{steps.vars.outputs.IMAGE_TAG}}"
